services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: wpulls
      POSTGRES_PASSWORD: wpulls
      POSTGRES_DB: wpulls
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-dev-data:/data

volumes:
  postgres-dev-data:
  redis-dev-data:
